openapi: 3.0.3
info:
  title: Cars24 Integration API
  description: API for Cars24 integration services
  version: 1.0.0
  contact:
    name: Cars24 Development Team
    email: dev@cars24.com
servers:
  - url: https://api.cars24.com/v1
    description: Production server
  - url: https://staging-api.cars24.com/v1
    description: Staging server
paths:
  /agents/scrub:
    post:
      summary: Scrub agents to get online agents
      description: Filter agents based on call ID, schedule ID and user metadata to return only online agents
      operationId: scrubAgents
      tags:
        - Agents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - call_id
                - schedule_id
                - meta
                - agents
              properties:
                call_id:
                  type: integer
                  description: Unique identifier for the call
                  example: 123456
                  minimum: 1
                schedule_id:
                  type: integer
                  description: Unique identifier for the schedule
                  example: 789
                  minimum: 1
                meta:
                  type: object
                  description: JSON object containing metadata
                  example: {"customer_id": "cust_123", "priority": "high", "location": "delhi"}
                  additionalProperties: true
                agents:
                  type: array
                  description: Array of agent email addresses to check
                  items:
                    type: string
                    format: email
                    example: "agent@cars24.com"
                  minItems: 1
                  maxItems: 100
            example:
              call_id: 123456
              schedule_id: 789
              meta:
                customer_id: "cust_123"
                priority: "high"
                location: "delhi"
              agents:
                - "agent1@cars24.com"
                - "agent2@cars24.com"
                - "agent3@cars24.com"
      responses:
        '200':
          description: Successfully retrieved online agents (may be empty if no agents are online)
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: Response status (1 for success, 0 for failure)
                    enum: [0, 1]
                    example: 1
                  agents:
                    type: array
                    description: Array of online agent email addresses (empty if no agents are online)
                    items:
                      type: string
                      format: email
                      example: "agent1@cars24.com"
              examples:
                with_agents:
                  summary: "Agents found online"
                  value:
                    status: 1
                    agents:
                      - "agent1@cars24.com"
                      - "agent2@cars24.com"
                no_agents:
                  summary: "No agents online"
                  value:
                    status: 1
                    agents: []
        '400':
          description: Bad request - Invalid input parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: Response status (1 for success, 0 for failure)
                    enum: [0, 1]
                    example: 0
                  agents:
                    type: array
                    description: Empty array for error responses
                    items:
                      type: string
                      format: email
                    example: []
        '401':
          description: Unauthorized - Invalid or missing authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: Response status (1 for success, 0 for failure)
                    enum: [0, 1]
                    example: 0
                  agents:
                    type: array
                    description: Empty array for error responses
                    items:
                      type: string
                      format: email
                    example: []
        '404':
          description: Not found - Call ID or Schedule ID not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: Response status (1 for success, 0 for failure)
                    enum: [0, 1]
                    example: 0
                  agents:
                    type: array
                    description: Empty array for error responses
                    items:
                      type: string
                      format: email
                    example: []
      security:
        - ApiKeyAuth: []
        - BearerAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for authentication
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication
  schemas:
    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: array
              items:
                type: string
tags:
  - name: Agents
    description: Operations related to agent management
